# Generated by Django 2.2.1 on 2019-05-21 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of Permission')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionChangeReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(unique=True, verbose_name='Reason of Substitution')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name of Position')),
                ('permissions', models.ManyToManyField(blank=True, to='app.Permission', verbose_name='Permissions of Position')),
            ],
        ),
        migrations.CreateModel(
            name='SubstitutionReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(unique=True, verbose_name='Reason of Substitution')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Worker')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname of Worker')),
                ('pesel', models.CharField(max_length=11, verbose_name='Pesel')),
                ('salary', models.IntegerField(verbose_name='Salary of Worker')),
                ('employment_date', models.DateField(verbose_name='Date when Worker was employed')),
                ('promotion_date', models.DateField(verbose_name='Date when Worker got promoted')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Position', verbose_name='Position of Worker')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Supervisor')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_begin', models.DateField(verbose_name='Date defining start of Substitution')),
                ('substitute_end', models.DateField(verbose_name='Date defining end of Substitution')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.SubstitutionReason', verbose_name='Reason for Substitution')),
                ('substituted_worker', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subbed', to='app.Worker', verbose_name='Worker to be Substituted')),
                ('substituting_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subbing', to='app.Worker', verbose_name='Worker Substituting other')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_begin', models.DateField(verbose_name='Date defining start of Substitution')),
                ('substitute_end', models.DateField(blank=True, null=True, verbose_name='Date defining end of Substitution')),
                ('new_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newpos', to='app.Position', verbose_name='New Position')),
                ('old_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldpos', to='app.Position', verbose_name='Old Position')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.PermissionChangeReason', verbose_name='Reason for Substitution')),
                ('subbed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='le_subbed', to='app.Worker', verbose_name='Worker to be Substituted')),
                ('subbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='le_subbing', to='app.Worker', verbose_name='Worker Substituting other')),
            ],
        ),
    ]
