version: '3'

services:
    postgres:
        container_name: bd2_container
        build: .
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
        volumes:
            - bd2:/data/postgres
        ports:
            - "5444:5432"
        networks:
            - bd2
        restart: unless-stopped

networks:
    bd2:
        driver: bridge

volumes:
    bd2:
